- name: "Calculate release"
  set_fact:
    release: "{{ macklus.os.repository.release | default(ansible_distribution_release) }}"

- name: "{{ ansible_distribution }} base repository"
  apt_repository:
    repo: "{{ item }}"
    state: present
  with_items:
    - deb http://{{ macklus.os.repository.country }}.archive.ubuntu.com/ubuntu/ {{ release }} main restricted universe multiverse 
    - deb-src http://{{ macklus.os.repository.country }}.archive.ubuntu.com/ubuntu/ {{ release }} main restricted universe multiverse 
    - deb http://{{ macklus.os.repository.country }}.archive.ubuntu.com/ubuntu/ {{ release }}-security main restricted universe multiverse 
    - deb http://{{ macklus.os.repository.country }}.archive.ubuntu.com/ubuntu/ {{ release }}-updates main restricted universe multiverse 
    - deb-src http://{{ macklus.os.repository.country }}.archive.ubuntu.com/ubuntu/ {{ release }}-security main restricted universe multiverse 
    - deb-src http://{{ macklus.os.repository.country }}.archive.ubuntu.com/ubuntu/ {{ release }}-updates main restricted universe multiverse 
  when: macklus.os.repository.install == true 