- name: Calculate latest packages
  set_fact:
    latest_packages: "{{ macklus.os.packages.latest.all + macklus.os.packages.latest.debian }}"

- name: Install required packages
  apt:
    name: "{{ latest_packages }}"
    state: latest
    update_cache: yes

- name: Calculate absent packages
  set_fact:
    absent_packages: "{{ macklus.os.packages.absent.all + macklus.os.packages.absent.debian }}"

- name: Remove required packages
  apt:
    name: "{{ absent_packages }}"
    state: absent