- name: Check that the /var/run/reboot-required exists
  stat:
    path: /var/run/reboot-required
  register: _var_run_reboot_required
  when: macklus.os.reboot == 'only_if_necessary'

- name: Force reboot (because is necessary)
  reboot:
  when: macklus.os.reboot == 'only_if_necessary' and _var_run_reboot_required.stat.exists

- name: Force reboot (always)
  reboot:
  when: macklus.os.reboot == 'always'
